# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  stripe_api_key: <%= ENV["SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>
  secret_key_base: 566743dec5b0d2dfa9dd99e09c18d267fac8103b3af524d5e1e4f8a34d6bed1e6cdd0e109ac6019b5677b52f4666bd8594c7a165d65466a09dfcebdeabd51acd


test:
  secret_key_base: 9c9a6a3d7453d7d97991446739d0386f3cb09722ddad811d71a3bfb31efe0924b7417423b24a6dc16058417cb573e52bb85f875374a519cae366c93ae818b167
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  stripe_api_key: <%= ENV["SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  stripe_api_key: <%= ENV["SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
